version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3004:3004"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=${MYSQL_PRODUCTION_HOST}
      - MYSQL_PORT=${MYSQL_PRODUCTION_PORT}
      - MYSQL_USERNAME=${MYSQL_PRODUCTION_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PRODUCTION_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_PRODUCTION_DB_NAME}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 